### ISSUE TITLE
Sanitize callback for this control type?

### ISSUE THREAD

**Issue by phankimi** [soderlind/class-customizer-toggle-control#1]
How do you write sanitize callback function for this toggle control type?
I've try sanitize as checkbox control type but it's not working.

**Comment by soderlind** [comment]
The control is a checkbox control, so any sanitize check for a checkbox should work, eg:

```php
function mytheme_chkbox_sanitization( $input ) {
   if ( true === $input ) {
      return 1;
   } else {
      return 0;
   }
}
```
The example above is from https://maddisondesigns.com/2017/05/the-wordpress-customizer-a-developers-guide-part-1/
