### ISSUE TITLE
can you make this control available on packagist.org?

### ISSUE THREAD

**Issue by pbiron** [soderlind/class-customizer-toggle-control#2]
Is there any way you could make this control available on packagist.org?  The same for https://github.com/soderlind/class-customizer-range-value-control.

I would like to use them in a plugin I'm developing and it would be a lot easier if they were on packagist.org.  During the early stages of my plugin's development I've just manually copied the relevant files into a sub-directory of `vendor/` in my plugin _as if_ they were actually managed by composer.

I notice that you already have https://packagist.org/packages/soderlind/acf-field-date-time-picker on packagist, so hopefully putting these Customizer controls there won't be too hard for you.

**Comment by pbiron** [comment]
Also, as part of publishing them on packagist, I think you change how `Customizer_Range_Value_Control::enqueue()` is written.

Instead of

```php
wp_enqueue_script( 'customizer-range-value-control', get_stylesheet_directory_uri() . '/js/customizer-range-value-control.js', array( 'jquery' ), rand(), true );
wp_enqueue_style( 'customizer-range-value-control', get_stylesheet_directory_uri() . '/css/customizer-range-value-control.css', array(), rand() );
```

it should be:

```php
wp_enqueue_script( 'customizer-range-value-control', __DIR__ . '/js/customizer-range-value-control.js', array( 'jquery' ), rand(), true );
wp_enqueue_style( 'customizer-range-value-control', __DIR__ . '/css/customizer-range-value-control.css', array(), rand() );
```

**Comment by soderlind** [comment]
@pbiron. If possible (being a lib), I'll add it to packagist soon. 

ref `__DIR__`, We can't use `__DIR__`,  `wp_enqueue_*` expect an url, not a file path. I chose `get_stylesheet_directory_uri()` since it points to the current (child) theme folder, but I'll have a look at it again before I add the code to packagist.

**Comment by pbiron** [comment]
> ref `__DIR__`, We can't use `__DIR__`, `wp_enqueue_*` expect an url, not a file path. I chose `get_stylesheet_directory_uri()` since it points to the current (child) theme folder, but I'll have a look at it again before I add the code to packagist.

Of course, my bad.   In addition to a URL, `$src` can also be a path relative to the dir WP is installed in.  And I had meant to include something about comparing `__DIR__`  to `ABSPATH` and munging accordingly.

The point was to make your code agnostic as to whether it is being used in a theme or a plugin.

**Comment by pbiron** [comment]
The following works for me (on a windows host):

```
$relative_to_abspath = wp_normalize_path( str_replace( rtrim( ABSPATH, '/' ), '', dirname( __FILE__ ) ) );

wp_enqueue_script( 'customizer-range-value-control', "{$relative_to_abspath}/js/customizer-range-value-control.js", array( 'jquery' ), rand(), true );
wp_enqueue_style( 'customizer-range-value-control', "{$relative_to_abspath}/css/customizer-range-value-control.css", array(), rand() );
```

**Comment by pbiron** [comment]
p.s. I can do a PR with that change (in both repos) if that you be easier for you.

**Comment by soderlind** [comment]
I could make the code agnostic using this (from https://wordpress.stackexchange.com/a/264870/14546):

```php
function abs_path_to_url( $path = '' ) {
    $url = str_replace(
        wp_normalize_path( untrailingslashit( ABSPATH ) ),
        site_url(),
        wp_normalize_path( $path )
    );
    return esc_url_raw( $url );
}
```

If you do a PR, I'd prefer that you add support for `composer/installers` in the composer file, like:

```javascript
"require": {
    "composer/installers": "~1.0" 
}
```

allowing others to do, in their composer file:
```javascript
"extra": {
    "installer-paths": {
      "inc/{$name}": ["soderlind/class-customizer-toggle-control"]
    }
}
```

The above composer examples are from https://www.ibenic.com/using-composer-for-libraries-in-wordpress-plugins-or-themes/

**Comment by pbiron** [comment]
sure.  Look for PRs.  Probably won't get to that until after the US holiday (Thanksgiving, which is tomorrow).

Speaking of thanksgiving, thank you for being open to publishing these on packagist!

**Comment by soderlind** [comment]
You don't have to do the PR, I'll fix it now. Thank you for reminding me about packagist.

Happy Thanksgiving :)

**Comment by soderlind** [comment]
done: https://packagist.org/packages/soderlind/

soon also https://github.com/soderlind/class-customizer-range-value-control

**Comment by pbiron** [comment]
Again, thank you for doing this!

I'm curious about a couple of things:

1. why the dependency on `php >= 7.0`?
    * It runs just fine on PHP 5.6.  I had to upgrade my PHP just to get install this...and then downgrade again (because I have other dependencies that need 5.6)
2. why the dependency on `composer/installers`?
    * it took me quite a while to figure out how to get it install into the normal `vendor` dir

Here's what I had to do in composer.json to get it install in `vendor`

```
"extra": {
	"installer-paths": {
		"vendor/soderlind/{$name}": [
			"soderlind/class-customizer-range-value-control",
			"soderlind/class-customizer-toggle-control"
		]
	}
}
```

**Comment by soderlind** [comment]
I changed the version to ` php >= 5.6`
